/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of:
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) nmpc_solver_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {17, 1, 1};
static const casadi_int casadi_s1[3] = {13, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[3] = {1, 17, 1};
static const casadi_int casadi_s4[3] = {1, 13, 1};

static const casadi_real casadi_c0[4] = {1.0000000000000001e-01, 5.0000000000000000e-01, 5.0000000000000000e-01, 5.0000000000000000e-01};

static const casadi_real casadi_zeros[13] =
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0.};

/* dynamics_sx:(x[13],u[4])->(xdot[13]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9;
  /* #0: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @0 = input[0][4] */
  w0 = arg[0] ? arg[0][4] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #4: @0 = input[0][5] */
  w0 = arg[0] ? arg[0][5] : 0;
  /* #5: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #6: @0 = input[0][7] */
  w0 = arg[0] ? arg[0][7] : 0;
  /* #7: @1 = input[0][9] */
  w1 = arg[0] ? arg[0][9] : 0;
  /* #8: @2 = (@0*@1) */
  w2  = (w0*w1);
  /* #9: @3 = input[0][6] */
  w3 = arg[0] ? arg[0][6] : 0;
  /* #10: @4 = input[0][8] */
  w4 = arg[0] ? arg[0][8] : 0;
  /* #11: @5 = (@3*@4) */
  w5  = (w3*w4);
  /* #12: @2 = (@2+@5) */
  w2 += w5;
  /* #13: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #14: @5 = 412.02 */
  w5 = 4.1202000000000004e+02;
  /* #15: @6 = input[1][0] */
  w6 = arg[1] ? arg[1][0] : 0;
  /* #16: @5 = (@5*@6) */
  w5 *= w6;
  /* #17: @2 = (@2*@5) */
  w2 *= w5;
  /* #18: @6 = 3.5 */
  w6 = 3.5000000000000000e+00;
  /* #19: @2 = (@2/@6) */
  w2 /= w6;
  /* #20: output[0][3] = @2 */
  if (res[0]) res[0][3] = w2;
  /* #21: @2 = (@4*@1) */
  w2  = (w4*w1);
  /* #22: @6 = (@3*@0) */
  w6  = (w3*w0);
  /* #23: @2 = (@2-@6) */
  w2 -= w6;
  /* #24: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #25: @2 = (@2*@5) */
  w2 *= w5;
  /* #26: @6 = 3.5 */
  w6 = 3.5000000000000000e+00;
  /* #27: @2 = (@2/@6) */
  w2 /= w6;
  /* #28: output[0][4] = @2 */
  if (res[0]) res[0][4] = w2;
  /* #29: @2 = -34.335 */
  w2 = -3.4335000000000001e+01;
  /* #30: @6 = 1 */
  w6 = 1.;
  /* #31: @7 = sq(@0) */
  w7 = casadi_sq( w0 );
  /* #32: @8 = sq(@4) */
  w8 = casadi_sq( w4 );
  /* #33: @7 = (@7+@8) */
  w7 += w8;
  /* #34: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #35: @6 = (@6-@7) */
  w6 -= w7;
  /* #36: @6 = (@6*@5) */
  w6 *= w5;
  /* #37: @2 = (@2+@6) */
  w2 += w6;
  /* #38: @6 = 3.5 */
  w6 = 3.5000000000000000e+00;
  /* #39: @2 = (@2/@6) */
  w2 /= w6;
  /* #40: output[0][5] = @2 */
  if (res[0]) res[0][5] = w2;
  /* #41: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #42: @6 = input[0][10] */
  w6 = arg[0] ? arg[0][10] : 0;
  /* #43: @5 = (@6*@0) */
  w5  = (w6*w0);
  /* #44: @5 = (-@5) */
  w5 = (- w5 );
  /* #45: @7 = input[0][11] */
  w7 = arg[0] ? arg[0][11] : 0;
  /* #46: @8 = (@7*@4) */
  w8  = (w7*w4);
  /* #47: @5 = (@5-@8) */
  w5 -= w8;
  /* #48: @8 = input[0][12] */
  w8 = arg[0] ? arg[0][12] : 0;
  /* #49: @9 = (@8*@1) */
  w9  = (w8*w1);
  /* #50: @5 = (@5-@9) */
  w5 -= w9;
  /* #51: @2 = (@2*@5) */
  w2 *= w5;
  /* #52: output[0][6] = @2 */
  if (res[0]) res[0][6] = w2;
  /* #53: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #54: @5 = (@6*@3) */
  w5  = (w6*w3);
  /* #55: @9 = (@8*@4) */
  w9  = (w8*w4);
  /* #56: @5 = (@5+@9) */
  w5 += w9;
  /* #57: @9 = (@7*@1) */
  w9  = (w7*w1);
  /* #58: @5 = (@5-@9) */
  w5 -= w9;
  /* #59: @2 = (@2*@5) */
  w2 *= w5;
  /* #60: output[0][7] = @2 */
  if (res[0]) res[0][7] = w2;
  /* #61: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #62: @5 = (@7*@3) */
  w5  = (w7*w3);
  /* #63: @9 = (@8*@0) */
  w9  = (w8*w0);
  /* #64: @5 = (@5-@9) */
  w5 -= w9;
  /* #65: @1 = (@6*@1) */
  w1  = (w6*w1);
  /* #66: @5 = (@5+@1) */
  w5 += w1;
  /* #67: @2 = (@2*@5) */
  w2 *= w5;
  /* #68: output[0][8] = @2 */
  if (res[0]) res[0][8] = w2;
  /* #69: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #70: @3 = (@8*@3) */
  w3  = (w8*w3);
  /* #71: @0 = (@7*@0) */
  w0  = (w7*w0);
  /* #72: @3 = (@3+@0) */
  w3 += w0;
  /* #73: @4 = (@6*@4) */
  w4  = (w6*w4);
  /* #74: @3 = (@3-@4) */
  w3 -= w4;
  /* #75: @2 = (@2*@3) */
  w2 *= w3;
  /* #76: output[0][9] = @2 */
  if (res[0]) res[0][9] = w2;
  /* #77: @2 = input[1][1] */
  w2 = arg[1] ? arg[1][1] : 0;
  /* #78: @3 = 0.08 */
  w3 = 8.0000000000000016e-02;
  /* #79: @3 = (@3*@7) */
  w3 *= w7;
  /* #80: @3 = (@3*@8) */
  w3 *= w8;
  /* #81: @2 = (@2-@3) */
  w2 -= w3;
  /* #82: @3 = 0.12 */
  w3 = 1.2000000000000000e-01;
  /* #83: @2 = (@2/@3) */
  w2 /= w3;
  /* #84: output[0][10] = @2 */
  if (res[0]) res[0][10] = w2;
  /* #85: @2 = input[1][2] */
  w2 = arg[1] ? arg[1][2] : 0;
  /* #86: @3 = -0.08 */
  w3 = -8.0000000000000016e-02;
  /* #87: @3 = (@3*@6) */
  w3 *= w6;
  /* #88: @3 = (@3*@8) */
  w3 *= w8;
  /* #89: @2 = (@2-@3) */
  w2 -= w3;
  /* #90: @3 = 0.12 */
  w3 = 1.2000000000000000e-01;
  /* #91: @2 = (@2/@3) */
  w2 /= w3;
  /* #92: output[0][11] = @2 */
  if (res[0]) res[0][11] = w2;
  /* #93: @2 = input[1][3] */
  w2 = arg[1] ? arg[1][3] : 0;
  /* #94: @3 = 0.2 */
  w3 = 2.0000000000000001e-01;
  /* #95: @2 = (@2/@3) */
  w2 /= w3;
  /* #96: output[0][12] = @2 */
  if (res[0]) res[0][12] = w2;
  return 0;
}

/* solver_fun:(z[17],x_ref[13])->(cost) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *w1=w+23, *w2=w+26, *w3=w+39, w4, w5, *w6=w+44, *w7=w+48, w8, *w9=w+53;
  const casadi_real **arg1=arg+2, *cr, *cs, *ct, *wr0, *wr1, *wr2, *wr3, *wr6, *wr7;
  /* #0: @0 = input[0][0] */
  wr0 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = @0[:3] */
  wr1 = wr0+0;
  /* #2: @2 = input[1][0] */
  wr2 = arg[1] ? arg[1] : casadi_zeros;
  /* #3: @3 = @2[:3] */
  wr3 = wr2+0;
  /* #4: @1 = (@1-@3) */
  for (i=0, rr=w1, cr=wr1, cs=wr3; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #5: @3 = all_10(3x1) */
  casadi_fill(w3, 3, 10.);
  /* #6: @3 = (@3*@1) */
  for (i=0, rr=w3, cs=w1; i<3; ++i) (*rr++) *= (*cs++);
  /* #7: @4 = dot(@1, @3) */
  w4 = casadi_dot(3, w1, w3);
  /* #8: @1 = @0[3:6] */
  wr1 = wr0+3;
  /* #9: @3 = @2[3:6] */
  wr3 = wr2+3;
  /* #10: @1 = (@1-@3) */
  for (i=0, rr=w1, cr=wr1, cs=wr3; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #11: @5 = dot(@1, @1) */
  w5 = casadi_dot(3, w1, w1);
  /* #12: @4 = (@4+@5) */
  w4 += w5;
  /* #13: @6 = @0[6:10] */
  wr6 = wr0+6;
  /* #14: @7 = @2[6:10] */
  wr7 = wr2+6;
  /* #15: @6 = (@6-@7) */
  for (i=0, rr=w6, cr=wr6, cs=wr7; i<4; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #16: @7 = all_5(4x1) */
  casadi_fill(w7, 4, 5.);
  /* #17: @7 = (@7*@6) */
  for (i=0, rr=w7, cs=w6; i<4; ++i) (*rr++) *= (*cs++);
  /* #18: @5 = dot(@6, @7) */
  w5 = casadi_dot(4, w6, w7);
  /* #19: @4 = (@4+@5) */
  w4 += w5;
  /* #20: @1 = @0[10:13] */
  wr1 = wr0+10;
  /* #21: @3 = @2[10:13] */
  wr3 = wr2+10;
  /* #22: @1 = (@1-@3) */
  for (i=0, rr=w1, cr=wr1, cs=wr3; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #23: @5 = dot(@1, @1) */
  w5 = casadi_dot(3, w1, w1);
  /* #24: @4 = (@4+@5) */
  w4 += w5;
  /* #25: @6 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+13 : 0, 4, w6);
  /* #26: @7 = [0.1, 0.5, 0.5, 0.5] */
  casadi_copy(casadi_c0, 4, w7);
  /* #27: @7 = (@7*@6) */
  for (i=0, rr=w7, cs=w6; i<4; ++i) (*rr++) *= (*cs++);
  /* #28: @5 = dot(@6, @7) */
  w5 = casadi_dot(4, w6, w7);
  /* #29: @4 = (@4+@5) */
  w4 += w5;
  /* #30: @5 = 0.01 */
  w5 = 1.0000000000000000e-02;
  /* #31: @8 = 0 */
  w8 = 0.;
  /* #32: @2 = ones(1x13) */
  casadi_fill(w2, 13, 1.);
  /* #33: @9 = dynamics_sx(@0, @6) */
  arg1[0]=wr0;
  arg1[1]=w6;
  res1[0]=w9;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #34: @9 = sq(@9) */
  for (i=0, rr=w9, cs=w9; i<13; ++i) *rr++ = casadi_sq( *cs++ );
  /* #35: @8 = mac(@2,@9,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w2+j, ct=w9+i*13; k<13; ++k) *rr += cs[k*1]**ct++;
  /* #36: @5 = (@5*@8) */
  w5 *= w8;
  /* #37: @4 = (@4+@5) */
  w4 += w5;
  /* #38: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

CASADI_SYMBOL_EXPORT int solver_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int solver_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int solver_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void solver_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int solver_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void solver_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void solver_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void solver_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int solver_fun_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int solver_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real solver_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* solver_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "z";
    case 1: return "x_ref";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* solver_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "cost";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* solver_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* solver_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int solver_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 66;
  return 0;
}

CASADI_SYMBOL_EXPORT int solver_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 66*sizeof(casadi_real);
  return 0;
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_solver_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_solver_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    default: return 0;
  }
}


#ifdef __cplusplus
} /* extern "C" */
#endif
