/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of:
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef NMPC_SOLVER_H
#define NMPC_SOLVER_H

#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

/**
 * @brief Main NMPC solver function
 *
 * Evaluates the objective function and constraints for the NMPC problem.
 *
 * @param arg Input arguments array:
 *            arg[0]: Decision variables (17x1) - [states(13); controls(4)]
 *            arg[1]: Parameters (1x1)
 * @param res Output results array:
 *            res[0]: Objective value (scalar)
 *            res[1]: Constraints (empty)
 * @param iw  Integer work vector
 * @param w   Real work vector (size: 64)
 * @param mem Memory object (use 0 for stateless operation)
 *
 * @return 0 on success, non-zero on error
 *
 * @example
 * // Input data
 * const casadi_real x[17] = {0, 0, 0, ...};  // states + controls
 * const casadi_real p[1] = {0};               // parameters
 * const casadi_real* arg[2] = {x, p};
 *
 * // Output data
 * casadi_real f_out;
 * casadi_real* res[2] = {&f_out, NULL};
 *
 * // Work arrays
 * casadi_real w[64];
 *
 * // Call solver
 * int status = solver_fun(arg, res, NULL, w, 0);
 */
CASADI_SYMBOL_EXPORT int solver_fun(const casadi_real** arg, casadi_real** res,
                                     casadi_int* iw, casadi_real* w, int mem);

/**
 * @brief Allocate memory for the solver
 * @return Memory identifier (0 if stateless)
 */
CASADI_SYMBOL_EXPORT int solver_fun_alloc_mem(void);

/**
 * @brief Initialize allocated memory
 * @param mem Memory identifier
 * @return 0 on success
 */
CASADI_SYMBOL_EXPORT int solver_fun_init_mem(int mem);

/**
 * @brief Free allocated memory
 * @param mem Memory identifier
 */
CASADI_SYMBOL_EXPORT void solver_fun_free_mem(int mem);

/**
 * @brief Checkout memory for thread-safe operation
 * @return Memory identifier
 */
CASADI_SYMBOL_EXPORT int solver_fun_checkout(void);

/**
 * @brief Release checked-out memory
 * @param mem Memory identifier
 */
CASADI_SYMBOL_EXPORT void solver_fun_release(int mem);

/**
 * @brief Increment reference count
 */
CASADI_SYMBOL_EXPORT void solver_fun_incref(void);

/**
 * @brief Decrement reference count
 */
CASADI_SYMBOL_EXPORT void solver_fun_decref(void);

/**
 * @brief Get number of inputs
 * @return Number of input arguments (2)
 */
CASADI_SYMBOL_EXPORT casadi_int solver_fun_n_in(void);

/**
 * @brief Get number of outputs
 * @return Number of output arguments (2)
 */
CASADI_SYMBOL_EXPORT casadi_int solver_fun_n_out(void);

/**
 * @brief Get default value for input
 * @param i Input index
 * @return Default value (0.0)
 */
CASADI_SYMBOL_EXPORT casadi_real solver_fun_default_in(casadi_int i);

/**
 * @brief Get name of input
 * @param i Input index
 * @return Name string ("i0" or "i1")
 */
CASADI_SYMBOL_EXPORT const char* solver_fun_name_in(casadi_int i);

/**
 * @brief Get name of output
 * @param i Output index
 * @return Name string ("o0" or "o1")
 */
CASADI_SYMBOL_EXPORT const char* solver_fun_name_out(casadi_int i);

/**
 * @brief Get sparsity pattern of input
 * @param i Input index
 * @return Sparsity descriptor array
 */
CASADI_SYMBOL_EXPORT const casadi_int* solver_fun_sparsity_in(casadi_int i);

/**
 * @brief Get sparsity pattern of output
 * @param i Output index
 * @return Sparsity descriptor array
 */
CASADI_SYMBOL_EXPORT const casadi_int* solver_fun_sparsity_out(casadi_int i);

/**
 * @brief Get required work vector sizes
 * @param sz_arg Size of argument pointer array (5)
 * @param sz_res Size of result pointer array (3)
 * @param sz_iw  Size of integer work array (0)
 * @param sz_w   Size of real work array (64)
 * @return 0 on success
 */
CASADI_SYMBOL_EXPORT int solver_fun_work(casadi_int *sz_arg, casadi_int* sz_res,
                                          casadi_int *sz_iw, casadi_int *sz_w);

/**
 * @brief Get required work vector sizes in bytes
 * @param sz_arg Size of argument pointer array in bytes
 * @param sz_res Size of result pointer array in bytes
 * @param sz_iw  Size of integer work array in bytes
 * @param sz_w   Size of real work array in bytes
 * @return 0 on success
 */
CASADI_SYMBOL_EXPORT int solver_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res,
                                                casadi_int *sz_iw, casadi_int *sz_w);

#ifdef __cplusplus
}
#endif

#endif /* NMPC_SOLVER_H */
